import { Inter } from "next/font/google";
import StyledComponentsRegistry, { GlobalStyled } from "@/lib/registry";
import Nav from "@/components/nav";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <title>OI</title>
      </head>
      <body>
        
          <GlobalStyled />
          <Nav />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        
      </body>
    </html>
  );
}
